tap "homebrew/bundle"
tap "homebrew/cask-fonts"

# dev stuff
brew "direnv"
brew "git"
brew "htop"
brew "node"
brew "openssl@3"
brew "pyenv"
brew "readline"
brew "starship"
brew "tmux"
brew "tree"
brew "zig"
brew "zlib"

# apps
cask "beekeeper-studio"
cask "chromedriver"
cask "docker"
cask "eloston-chromium"
cask "figma"
cask "miro"
cask "slack"
cask "visual-studio-code"
cask "zoom"
cask "logseq"
cask "anytype"
cask "bitwarden"
cask "zed"
cask "tsh"
cask "linearmouse"

# fonts
cask "font-blex-mono-nerd-font"
cask "font-jetbrains-mono-nerd-font"
