#!/bin/sh

export PATH=$PATH:~/.cargo/bin
export PATH=$PATH:~/.docker/bin
export STARSHIP_CONFIG=~/.config/starship/starship.toml

# tell homebrew to not autoupdate every single time I run it (just once a week)
export HOMEBREW_AUTO_UPDATE_SECS=604800

# disable conda autoinit
export CONDA_AUTO_ACTIVATE_BASE=false

eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(pyenv init -)"
eval "$(pyenv init --path)"
eval "$(starship init zsh)"
eval "$(direnv hook zsh)"
eval "$(conda "shell.$(basename "${SHELL}")" hook)"
