#!/bin/sh

export PATH=$PATH:~/.cargo/bin
export PATH=$PATH:~/.docker/bin
export STARSHIP_CONFIG=~/.config/starship/starship.toml

eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(pyenv init -)"
eval "$(pyenv init --path)"
eval "$(starship init zsh)"
eval "$(direnv hook zsh)"
